version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
        - "5672:5672" 
        - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=wejo
      - RABBITMQ_DEFAULT_PASS=wejo
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq  # Persistent volume for RabbitMQ
    networks:
      - wejo-network
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "rabbitmqctl", "status"]
        interval: 10s
        timeout: 5s
        retries: 10

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra  # Persistent volume for Cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=wejo_cluster
    networks:
      - wejo-network
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=3boyteam
      - POSTGRES_PASSWORD=QwerPoiu@2025
      - POSTGRES_DB=dev_wejo
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent volume for PostgreSQL
    networks:
      - wejo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U 3boyteam -d dev_wejo"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  notification-service:
    image: lemichael52/wejo_notification_service
    build:
      context: .
      dockerfile: Wejo.Notification.API/Dockerfile
      args:
        ENVIRONMENT: Development
    container_name: wejo_notification_service
    ports:
      - "8084:8084"
    environment:
      - Wejo_Com_Environment=local
      - Wejo_Ide_Db_Host=postgres  # Update to use container name
      - Wejo_Ide_Db_Port=5432
      - Wejo_Ide_Db_Name=dev_wejo
      - Wejo_Ide_Db_UserName=3boyteam
      - Wejo_Ide_Db_Password=QwerPoiu@2025
      - Wejo_Ide_SwaggerEnabled=TRUE
      - Wejo_Ide_DevMode=TRUE
      - Wejo_Ide_Protocols="Http1_8081"
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
    networks:
      - wejo-network

  realtime-service:
    image: lemichael52/wejo_realtime_service
    build:
      context: .
      dockerfile: Wejo.Realtime.API/Dockerfile
      args:
        ENVIRONMENT: Development
    container_name: wejo_realtime_service
    ports:
      - "8083:8083"
      - "5001:5001"
    environment:
      - Wejo_Com_Environment=local
      - Wejo_Ide_Db_Host=postgres  # Update to use container name
      - Wejo_Ide_Db_Port=5432
      - Wejo_Ide_Db_Name=dev_wejo
      - Wejo_Ide_Db_UserName=3boyteam
      - Wejo_Ide_Db_Password=QwerPoiu@2025
      - Wejo_Ide_SwaggerEnabled=TRUE
      - Wejo_Ide_DevMode=TRUE
      - ASPNETCORE_URLS=http://+:8083;http://+:5001
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    networks:
      - wejo-network

  game-service:
    image: lemichael52/wejo_game_service
    build:
      context: .
      dockerfile: Wejo.Game.API/Dockerfile
      args:
        ENVIRONMENT: Development
    container_name: wejo_game_service
    ports:
      - "8081:8081"
    environment:
      - Wejo_Com_Environment=local
      - Wejo_Ide_Db_Host=postgres  # Update to use container name
      - Wejo_Ide_Db_Port=5432
      - Wejo_Ide_Db_Name=dev_wejo
      - Wejo_Ide_Db_UserName=3boyteam
      - Wejo_Ide_Db_Password=QwerPoiu@2025
      - Wejo_Ide_SwaggerEnabled=TRUE
      - Wejo_Ide_DevMode=TRUE
      - Wejo_Ide_Protocols="Http1_8081"
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcClient__NotificationService=https://wejo_realtime_service:5001
    depends_on:
      cassandra:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - wejo-network
    restart: unless-stopped

  identity-service:
    image: lemichael52/wejo_identity_service
    build:
      context: .
      dockerfile: Wejo.Identity.API/Dockerfile
      args:
        ENVIRONMENT: Development
    container_name: wejo_identity_service
    ports:
      - "8080:8080"
    depends_on:
      - game-service
      - postgres
    environment:
      - Wejo_Com_Environment=local
      - Wejo_Ide_Db_Host=postgres  # Update to use container name
      - Wejo_Ide_Db_Port=5432
      - Wejo_Ide_Db_Name=dev_wejo
      - Wejo_Ide_Db_UserName=3boyteam
      - Wejo_Ide_Db_Password=QwerPoiu@2025
      - Wejo_Ide_SwaggerEnabled=TRUE
      - Wejo_Ide_DevMode=TRUE
      - Wejo_Ide_Protocols="Http1_8085"
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - wejo-network

  job-service:
    image: lemichael52/wejo_job_service
    build:
      context: .
      dockerfile: Wejo.Backgroud.Job/Dockerfile
      args:
        ENVIRONMENT: Development
    container_name: wejo_job_service
    ports:
      - "8082:8082"
    depends_on:
      - identity-service
      - game-service
      - postgres
    environment:
      - Wejo_Com_Environment=local
      - Wejo_Job_Db_Host=postgres  # Update to use container name
      - Wejo_Job_Db_Port=5432
      - Wejo_Job_Db_Name=dev_wejo
      - Wejo_Job_Db_UserName=3boyteam
      - Wejo_Job_Db_Password=QwerPoiu@2025
      - Wejo_Job_SwaggerEnabled=TRUE
      - Wejo_Job_DevMode=TRUE
      - Wejo_Job_Protocols="Http1_8080"
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - wejo-network

volumes:
  cassandra-data:
  rabbitmq-data:
  postgres-data:

networks:
  wejo-network:
    driver: bridge