version: '3.8'

services:
  game-service:
    image: lemichael52/wejo_game_service 
    build:
      context: .
      dockerfile: Wejo.GameService.API/Dockerfile
      args:
        ENVIRONMENT: Development
    container_name: wejo_game_service
    ports:
      - "8081:8081"  # First argument mapping for game-service
    environment:
      - Wejo_Com_Environment=local
      - Wejo_Ide_Db_Host=34.142.173.238
      - Wejo_Ide_Db_Port=5432
      - Wejo_Ide_Db_Name=dev_wejo
      - Wejo_Ide_Db_UserName=3boyteam
      - Wejo_Ide_Db_Password=QwerPoiu@2025
      - Wejo_Ide_SwaggerEnabled=TRUE
      - Wejo_Ide_DevMode=TRUE
      - Wejo_Ide_Protocols="Http1_8081"
      - ASPNETCORE_ENVIRONMENT=Development

  identity-service:
    image: lemichael52/wejo_identity_service
    build:
      context: .
      dockerfile: Wejo.Identity.API/Dockerfile
      args:
        ENVIRONMENT: Development
    container_name: wejo_identity_service
    ports:
      - "8080:8080"  # First argument mapping for identity-service
    depends_on:
      - game-service  # Ensures game-service starts first
    environment:
      - Wejo_Com_Environment=local
      - Wejo_Ide_Db_Host=34.142.173.238
      - Wejo_Ide_Db_Port=5432
      - Wejo_Ide_Db_Name=dev_wejo
      - Wejo_Ide_Db_UserName=3boyteam
      - Wejo_Ide_Db_Password=QwerPoiu@2025
      - Wejo_Ide_SwaggerEnabled=TRUE
      - Wejo_Ide_DevMode=TRUE
      - Wejo_Ide_Protocols="Http1_8080"
      - ASPNETCORE_ENVIRONMENT=Development
